# Generated by Django 4.2.7 on 2024-03-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orderhistory_order_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderhistory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='products',
            field=models.ManyToManyField(through='home.OrderedProduct', to='home.product'),
        ),
    ]
